/**
 * Mock data generator for vector search playground
 * Generates realistic sample documents for demonstration
 */

export interface MockDocument {
  id: string;
  title: string;
  content: string;
}

/**
 * Generate mock documents for vector search
 */
export function generateMockDocuments(): MockDocument[] {
  return [
    {
      id: 'doc-1',
      title: 'TypeScript Introduction',
      content: 'TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It adds optional static typing to the language. TypeScript enables developers to catch errors at compile time rather than runtime, improving code quality and maintainability. The language supports interfaces, generics, and advanced type features that make large-scale application development more manageable.',
    },
    {
      id: 'doc-2',
      title: 'JavaScript Overview',
      content: 'JavaScript is a versatile programming language used for web development, server-side programming with Node.js, and more. It is the primary language for interactive web pages and has evolved significantly since its inception. JavaScript supports functional programming, object-oriented programming, and event-driven programming paradigms. Modern JavaScript includes features like async/await, destructuring, and modules.',
    },
    {
      id: 'doc-3',
      title: 'React Framework',
      content: 'React is a JavaScript library for building user interfaces with reusable components. It uses a virtual DOM for efficient rendering and updates. React follows a component-based architecture where each component manages its own state and lifecycle. The library emphasizes declarative programming, making it easier to reason about UI changes. React has become the most popular frontend framework in the JavaScript ecosystem.',
    },
    {
      id: 'doc-4',
      title: 'LangChain Framework',
      content: 'LangChain is a framework for developing applications powered by language models. It provides tools for chains, agents, and memory management. LangChain simplifies the process of building complex applications that leverage large language models. The framework includes components for prompt management, output parsing, and integration with various LLM providers. It enables developers to create sophisticated AI applications with minimal boilerplate code.',
    },
    {
      id: 'doc-5',
      title: 'RAG Concept',
      content: 'RAG (Retrieval-Augmented Generation) combines document retrieval with language model generation for more accurate responses. This approach retrieves relevant documents from a knowledge base and uses them as context for generating answers. RAG improves the accuracy and relevance of LLM responses by grounding them in factual information. It reduces hallucinations and enables the model to provide citations for its answers. RAG is particularly useful for question-answering systems and knowledge-intensive applications.',
    },
    {
      id: 'doc-6',
      title: 'Vector Databases',
      content: 'Vector databases are specialized databases designed to store and search high-dimensional vectors efficiently. They use techniques like approximate nearest neighbor search to find similar vectors quickly. Vector databases are essential for semantic search, recommendation systems, and machine learning applications. Popular vector databases include Pinecone, Weaviate, and Milvus. They enable efficient similarity search across millions or billions of vectors.',
    },
    {
      id: 'doc-7',
      title: 'Embeddings and Semantic Search',
      content: 'Embeddings are numerical representations of text that capture semantic meaning. They are generated by neural networks and allow for semantic similarity comparisons. Semantic search uses embeddings to find documents with similar meaning rather than exact keyword matches. This approach is more powerful than traditional keyword-based search for understanding user intent. Embeddings enable applications like recommendation systems, duplicate detection, and semantic clustering.',
    },
    {
      id: 'doc-8',
      title: 'Machine Learning Basics',
      content: 'Machine learning is a subset of artificial intelligence that enables systems to learn from data without being explicitly programmed. It involves training models on datasets to recognize patterns and make predictions. Common machine learning tasks include classification, regression, clustering, and dimensionality reduction. Machine learning powers many modern applications including recommendation systems, image recognition, and natural language processing.',
    },
  ];
}

/**
 * Get a mock document by ID
 */
export function getMockDocumentById(id: string): MockDocument | undefined {
  const docs = generateMockDocuments();
  return docs.find(doc => doc.id === id);
}

/**
 * Get all mock documents
 */
export function getAllMockDocuments(): MockDocument[] {
  return generateMockDocuments();
}

